### PR TITLE
Implement proofs for edge labelled graphs and dioids

### PR DESCRIPTION
**Pull request by anfelor**
This pull request is an implementation of the laws in  #https://github.com/snowleopard/alga/issues/17.
It is a first draft and needs a little bit of refactoring, specifically:

 1. What do you think of the new directory structure?
 2. The right-distributivity proof is a bit long, maybe unnecessarily so?
 3. ShortestDistances has no Theorems file yet.
 4. Some functions use camelCase.

But aside from that everything is there: A dioid implementation with laws, a bool instance with a proof of adherence to the laws, a labelled graph with laws and a proof that every labelled graph is a normal graph. What do you think?

### CODE REVIEW

**Comment by anfelor** [comment]
Ah, and I switched to the notation `x -[ r ]> y` in Ascii, since ` x < r > y` looked to confusing.Tell me if you want something else.

**Comment by snowleopard** [comment]
@anfelor Wow, it's an amazing PR. Many thanks! Everything looks perfect. 

There are a couple of pleasant surprises -- I didn't expect that associativity and distributivity will be demoted to mere theorems.

> Ah, and I switched to the notation `x -[ r ]> y` in Ascii, since `x < r > y` looked to confusing.

What about `x [ r ]> y`? It might look a bit less noisy, yet still not confusing. I've seen this notation used sometimes instead of a labelled arrow.

> Tell me if you want something else.

Please update the CI script -- at the moment it checks only a subset of files, see the build log:

https://travis-ci.org/algebraic-graphs/agda/builds/365695373

Also, let's update the README.

**Comment by snowleopard** [comment]
> The right-distributivity proof is a bit long, maybe unnecessarily so?

@anfelor I've pushed a commit with some simplification by factoring out left/right absorption.

**Comment by anfelor** [comment]
> I've pushed a commit with some simplification by factoring out left/right absorption.

@snowleopard Looks good, thank you!

I have pushed three commits for camel case, travis and the notation you proposed. I found the travis ci process a little bit confusing so I settled on the approach of the agda stdlib. If you want to know whether your new changes are actually valid, you run './index.sh' and then 'agda -i . -i src/ index.agda'. The newly created file will be overridden every time you invoke './index.sh' and not appear in git commits thanks to .gitignore. Maybe the 'agda -i . -i src/ index.agda' part should be part of the script?

**Comment by snowleopard** [comment]
@anfelor Thank you! 

> Maybe the 'agda -i . -i src/ index.agda' part should be part of the script?

What about making a single script called `verify.sh` that both finds the sources and invokes Agda? I think that would be convenient. The source-finding part is likely pretty cheap and does not need to be cached.

**Comment by anfelor** [comment]
> The source-finding part is likely pretty cheap and does not need to be cached.

@snowleopard It wasn't being cached in the first place so I just adopted your suggestion. In the last travis build the step took two and a half seconds, so it is indeed cheap enough to just run it every time.

**Comment by snowleopard** [comment]
@anfelor Awesome! Happy to merge this unless you plan to do anything else. An update to README would be nice, but I'm fine doing it myself, perhaps, adding some more details about what's going on in various files. So, it's up to you.

**Comment by anfelor** [comment]
@snowleopard Except for adding a proof that `ShortestDistance` is actually a dioid (which I currently don't have time to do and which wouldn't provide much value anyway), I think the pull request is ready for merging :+1:

**Comment by snowleopard** [comment]
Merged, thanks again!

**Comment by Rotsor** [comment]
I might be late to the party, but the `Dioid` data type doesn't look right to me. I'm pretty sure that as it stands one can prove that `Dioid` is isomorphic to `Bool`, but it feels that the intention was for it to be more abstract than that. (usually for algebraic structures we talk about "any set that satisfies certain properties" rather than "the minimal set that satisfies those same properties", because the minimal one is sometimes too boring; at least we're lucky to not end up with `Unit`).

**Comment by snowleopard** [comment]
@Rotsor How is `Dioid` isomorphic to `Bool`?

The intention is to encode the laws of an *idempotent semiring*:

https://ncatlab.org/nlab/show/idempotent+semiring

Are you saying this particular Agda encoding is incorrect, or are saying that in general dioids are isomorphic to Boolean algebras?

**Comment by Rotsor** [comment]
Yes, I'm saying that this encoding is incorrect. More precisely I claim I can write a function 

    bool-dioid-inverse : Bool -> Dioid

and then I'll be able to prove:

    bool-dioid-1 : ∀ {x : Bool} -> Bool._≡_ x (bool-dioid (bool-dioid-inverse x))
    bool-dioid-2 : ∀ {x : Dioid} -> Dioid._≡_ x (bool-dioid-inverse (bool-dioid x))

It's not hard to see why: the only allowed values of a dioid are 0, 1 and various sums of products thereof. We know addition and multiplication are distributive so it must be a top-level sum of products (DNF?); clauses containing zero work out to 0, products not containing 0 work out to 1, so everything reduces to "1+1+1+1...+1", and then we notice idempotence of addition so any such sum reduces to "1" (except for the empty sum).

**Comment by snowleopard** [comment]
@Rotsor Aha, I see! So, we need to parameterise dioids with a set of elements `A`, similarly to `Graph`?

**Comment by anfelor** [comment]
@Rotsor You are right and (even worse) the current implementation doesn't allow us to put anything useful into a LabelledGraph.

@snowleopard No, I am afraid that that won't be enough since just adding an `Element : A -> Dioid A` constructor doesn't allow us to look inside that constructor to see if it hides a zero or a one. Probably it  boils down to a redesign of the data type.

On the other hand, is this a high priority? Of course, we can't check that other dioids fulfill the laws but we can use it to prove theorems about LabelledGraph, so maybe just renaming it would be enough?

Am 24. April 2018 18:25:29 MESZ schrieb Andrey Mokhov <notifications@github.com>:
>@Rotsor Aha, I see! So, we need to parameterise dioids with a set of
>elements `A`, similarly to `Graph`?

**Comment by Rotsor** [comment]
Yeah, if you just add a constructor you don't quite get the full generality: what you get is the [free](https://en.wikipedia.org/wiki/Free_object) dioid, not an arbitrary one. And not every dioid instance can be expressed as a free one (but many can). For example the "trivial" dioid where 0=1 can never be expressed, doesn't matter what type you choose for your "element".

For a proper encoding you probably want something like [IsGraph](https://github.com/Rotsor/phd/blob/no-parameters/PG/GraphAlgebra.agda#L19), the trick which I borrowed from https://github.com/agda/agda-stdlib/blob/master/src/Algebra.agda, and which is also logically equivalent to your use of type classes in Haskell version.

That said, adding a constructor is already something (at least it no longer reduces to `Bool`).

Another possibility is to just `postulate` the type and its constructors (as functions) without declaring it an inductive type. Then you can't pattern-match on it, so Agda effectively doesn't "know" anything about that type. (which is kind of what we want to express)

**Comment by Rotsor** [comment]
> we can use it to prove theorems about LabelledGraph

(assuming "it" refers to the "secretly a Bool" incarnation of Dioid), we can only use it to prove theorems about graph labelled by `Bool`, which is exactly the same as normal graph, so it's hard to know that what we end up proving still applies if we have something else as labels.

**Comment by anfelor** [comment]
>you probably want something like IsGraph, 

@Rotsor Thank you for the link!

> (assuming "it" refers to the "secretly a Bool" incarnation of Dioid), we can only use it to prove theorems about graph labelled by Bool,

How so? The `Dioid` type is isomorphic to `Bool` only under it's equivalence relation, and the graph laws follow not from the `Bool` data type but from the dioid laws? In fact, you can't write an isomorphism between `Bool` and `Dioid` since `bool-dioid` is surjective but not injective and `inverse-bool-dioid` is injective but not surjective.

As you wrote `Dioid` is currently the minimal set for which the laws hold, so if something follows from the minimal set it should follow for all sets (which implement the laws)? Or am I missing something?

**Comment by Rotsor** [comment]
> only under it's equivalence relation

You normally either consider the set of equivalence classes under the equivalence relation, or without it, but not both at the same time.

If you do take the equivalence relation into account then this setoid (set of equivalence classes) is isomorphic to `Bool` in the sense that I wrote.
If you don't then it's no longer isomorphic, but the dioid laws no longer hold, so its a bit strange (why do we suddenly care about distinguishing `(a+b)+c` from `a+(b+c)`?).

>  if something follows from the minimal set it should follow for all sets (which implement the laws)? Or am I missing something?

Above I had an example of a property that holds for Bool, but not for arbitrary dioid, namely "0 != 1". (actually, the `Unit` dioid is smaller than `Bool` in some sense, so I'm not even sure what the precise notion of "minimal" is in which `Bool` is minimal).

**Comment by anfelor** [comment]
> If you don't then it's no longer isomorphic, but the dioid laws no longer hold, so its a bit strange (why do we suddenly care about distinguishing (a+b)+c from a+(b+c)?).

Ah, yes I see. I guess you are right that we need a new dioid data type and I am going to implement it this week. But just to help me understand Agda better:

> Above I had an example of a property that holds for Bool, but not for arbitrary dioid, namely "0 != 1". 

Yes, but it doesn't follow that in every dioid interpretation "0 != 1", doesn't it? More specifically, we can define a unit data type which is fulfills the dioid laws: https://gist.github.com/anfelor/7f5211c10223d253ece614fdfa2e662a

So my understanding at the moment is that while `Dioid` is wrong in that it can't express any interesting `Dioid`s the graph laws (which follow only from the dioid laws) are still correct.

**Comment by Rotsor** [comment]
> Yes, but it doesn't follow that in every dioid interpretation "0 != 1", doesn't it?

Exactly! But you could reach the opposite conclusion if you assumed what you wrote above:

> if something follows from the minimal set it should follow for all sets

**Comment by Rotsor** [comment]
> the graph laws (which follow only from the dioid laws) are still correct

Possibly, but one would have to check the proofs to be sure: maybe you pattern-matched on the dioid somewhere, which would render the proof invalid. Ideally such proof checking would be done by your proof checker (agda). :-)

**Comment by anfelor** [comment]
> maybe you pattern-matched on the dioid somewhere, which would render the proof invalid.

... because a dioid is not necessarily zero, one, or the addition or mulitplication of two dioids. And the problem with `a-dioid-lawful : ∀ {r s : Dioid} -> r Algebra.Dioid.≡ s -> a-dioid r ≡ a-dioid s` functions is that they check compliance with the laws only on the set `{zero, one}`, e.g. a `+` instance which isn't commutative except on that set would be identified as law-abiding.

Thank you!

**Comment by Rotsor** [comment]
Yes! Good job identifying the actual impact.

**Pull request merged**
